services:
  found-app:
    build: .
    container_name: found-app
    restart: unless-stopped
    environment:
      - NTFY_TOPIC=${NTFY_TOPIC}
    networks:
      - proxy

networks:
  proxy:
    external: true